# Blog info
blog_name: IamTing93
slogan: 窗外花又开
url: https://iamting93.github.io/

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /images/favicon.ico

# For seo
keywords: IamTing93, 

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: Github
    url: https://github.com/IamTing93
    target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 盒子

search_slogan:
  isShow: true # true|fase
  text: 搜索喜爱的文章

# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

donation:
  show: false
  btn_text: 支持一下
  tip: 扫一扫，支持forsigner
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
# blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST

# gitment comment service
gitment:
  enable: true
  mint: true
  count: true
  lazy: false
  cleanly: false
  language:
  owner: IamTing93
  repo: blog_comments
  oauth:
    client_id: 4f5c50c79d1d6d7b3676
    client_secret: 84b229e245d0fb9f11351054c3bc93285606fa95
  proxy_gateway:
  redirect_protocol:
    
# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "后端开发工程师，python爱好者"
    - "徒步旅游，摄影读书，还有公益和动漫"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@IamTing93"
    text_value_url: https://github.com/IamTing93
  - type: mail
    icon: icon-mail
    text_key: 邮箱
    text_value: "IamTing93@163.com"
  - type: location
    icon: icon-location
    text_value: 广州